// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frontline_route_revision.sql

package db

import (
	"context"
)

const findFrontlineRouteRevision = `-- name: FindFrontlineRouteRevision :one
SELECT CAST(
  COALESCE(
    (SELECT revision FROM frontline_route_revisions WHERE id = 1),
    0
  ) AS SIGNED
) AS revision
`

// FindFrontlineRouteRevision
//
//	SELECT CAST(
//	  COALESCE(
//	    (SELECT revision FROM frontline_route_revisions WHERE id = 1),
//	    0
//	  ) AS SIGNED
//	) AS revision
func (q *Queries) FindFrontlineRouteRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, findFrontlineRouteRevision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
