// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_find_by_fqdn.sql

package db

import (
	"context"
	"database/sql"
)

const findFrontlineRouteByFQDN = `-- name: FindFrontlineRouteByFQDN :one
SELECT
  fr.environment_id,
  fr.deployment_id,
  COALESCE(public_dr.id, '') AS resource_id,
  COALESCE(public_dr.name, '') AS resource_name,
  COALESCE(public_dr.kind, '') AS resource_kind,
  d.workspace_id,
  d.project_id,
  d.app_id,
  d.sentinel_config,
  d.upstream_protocol,
  da.name AS static_output_name,
  da.storage_key AS static_storage_key,
  da.digest AS static_digest,
  da.metadata AS static_metadata
FROM frontline_routes fr
INNER JOIN deployments d ON fr.deployment_id = d.id
LEFT JOIN deployment_resources public_dr
  ON public_dr.deployment_id = d.id
  AND public_dr.public = true
  AND public_dr.pk = (
    SELECT MIN(candidate.pk)
    FROM deployment_resources candidate
    WHERE candidate.deployment_id = d.id AND candidate.public = true
  )
LEFT JOIN deployment_artifacts da
  ON da.deployment_id = d.id
  AND da.kind = 'static_bundle'
WHERE fr.fully_qualified_domain_name = ?
`

type FindFrontlineRouteByFQDNRow struct {
	EnvironmentID    string                      `db:"environment_id"`
	DeploymentID     string                      `db:"deployment_id"`
	ResourceID       string                      `db:"resource_id"`
	ResourceName     string                      `db:"resource_name"`
	ResourceKind     DeploymentResourcesKind     `db:"resource_kind"`
	WorkspaceID      string                      `db:"workspace_id"`
	ProjectID        string                      `db:"project_id"`
	AppID            string                      `db:"app_id"`
	SentinelConfig   []byte                      `db:"sentinel_config"`
	UpstreamProtocol DeploymentsUpstreamProtocol `db:"upstream_protocol"`
	StaticOutputName sql.NullString              `db:"static_output_name"`
	StaticStorageKey sql.NullString              `db:"static_storage_key"`
	StaticDigest     sql.NullString              `db:"static_digest"`
	StaticMetadata   []byte                      `db:"static_metadata"`
}

// FindFrontlineRouteByFQDN resolves a hostname to the routing data frontline
// needs on the request path: the deployment ID, the policy bytes the engine
// evaluates, and the upstream protocol used to pick a transport. Joining
// deployments here keeps the fast path to a single round trip.
//
//	SELECT
//	  fr.environment_id,
//	  fr.deployment_id,
//	  COALESCE(public_dr.id, '') AS resource_id,
//	  COALESCE(public_dr.name, '') AS resource_name,
//	  COALESCE(public_dr.kind, '') AS resource_kind,
//	  d.workspace_id,
//	  d.project_id,
//	  d.app_id,
//	  d.sentinel_config,
//	  d.upstream_protocol,
//	  da.name AS static_output_name,
//	  da.storage_key AS static_storage_key,
//	  da.digest AS static_digest,
//	  da.metadata AS static_metadata
//	FROM frontline_routes fr
//	INNER JOIN deployments d ON fr.deployment_id = d.id
//	LEFT JOIN deployment_resources public_dr
//	  ON public_dr.deployment_id = d.id
//	  AND public_dr.public = true
//	  AND public_dr.pk = (
//	    SELECT MIN(candidate.pk)
//	    FROM deployment_resources candidate
//	    WHERE candidate.deployment_id = d.id AND candidate.public = true
//	  )
//	LEFT JOIN deployment_artifacts da
//	  ON da.deployment_id = d.id
//	  AND da.kind = 'static_bundle'
//	WHERE fr.fully_qualified_domain_name = ?
func (q *Queries) FindFrontlineRouteByFQDN(ctx context.Context, fqdn string) (FindFrontlineRouteByFQDNRow, error) {
	row := q.db.QueryRowContext(ctx, findFrontlineRouteByFQDN, fqdn)
	var i FindFrontlineRouteByFQDNRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.ResourceID,
		&i.ResourceName,
		&i.ResourceKind,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.SentinelConfig,
		&i.UpstreamProtocol,
		&i.StaticOutputName,
		&i.StaticStorageKey,
		&i.StaticDigest,
		&i.StaticMetadata,
	)
	return i, err
}
