// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_runtime_settings_find_sentinel_config.sql

package db

import (
	"context"
)

const findSentinelConfigByAppAndEnv = `-- name: FindSentinelConfigByAppAndEnv :one

SELECT sentinel_config
FROM app_runtime_settings
WHERE app_id = ?
  AND environment_id = ?
`

type FindSentinelConfigByAppAndEnvParams struct {
	AppID         string `db:"app_id"`
	EnvironmentID string `db:"environment_id"`
}

// Policy reads and writes only need the sentinel blob; use
// FindAppRuntimeSettingsByAppAndEnv when the full settings row is needed.
//
//	SELECT sentinel_config
//	FROM app_runtime_settings
//	WHERE app_id = ?
//	  AND environment_id = ?
func (q *Queries) FindSentinelConfigByAppAndEnv(ctx context.Context, db DBTX, arg FindSentinelConfigByAppAndEnvParams) ([]byte, error) {
	row := db.QueryRowContext(ctx, findSentinelConfigByAppAndEnv, arg.AppID, arg.EnvironmentID)
	var sentinel_config []byte
	err := row.Scan(&sentinel_config)
	return sentinel_config, err
}
