// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_delete_by_id.sql

package db

import (
	"context"
)

const deleteAppById = `-- name: DeleteAppById :exec
DELETE app_framework_detections, apps
FROM apps
LEFT JOIN app_framework_detections ON app_framework_detections.app_id = apps.id
WHERE apps.id = ?
`

// DeleteAppById
//
//	DELETE app_framework_detections, apps
//	FROM apps
//	LEFT JOIN app_framework_detections ON app_framework_detections.app_id = apps.id
//	WHERE apps.id = ?
func (q *Queries) DeleteAppById(ctx context.Context, db DBTX, id string) error {
	_, err := db.ExecContext(ctx, deleteAppById, id)
	return err
}
