// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkRecordDeploymentTargetAssignment is the base query for bulk insert
const bulkRecordDeploymentTargetAssignment = `INSERT INTO deployment_target_assignments ( id, target_id, workspace_id, project_id, app_id, environment_id, deployment_id, previous_deployment_id, reason, operation_id, created_at ) VALUES %s ON DUPLICATE KEY UPDATE id = id`

// RecordDeploymentTargetAssignment performs bulk insert in a single query
func (q *BulkQueries) RecordDeploymentTargetAssignment(ctx context.Context, db DBTX, args []RecordDeploymentTargetAssignmentParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkRecordDeploymentTargetAssignment, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.TargetID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.DeploymentID)
		allArgs = append(allArgs, arg.PreviousDeploymentID)
		allArgs = append(allArgs, arg.Reason)
		allArgs = append(allArgs, arg.OperationID)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
