// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertDeploymentResource is the base query for bulk insert
const bulkInsertDeploymentResource = `INSERT INTO deployment_resources ( id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, bindings, allowed_callers, cpu_millicores, memory_mib, storage_mib, created_at ) VALUES %s ON DUPLICATE KEY UPDATE id = id`

// InsertDeploymentResources performs bulk insert in a single query
func (q *BulkQueries) InsertDeploymentResources(ctx context.Context, db DBTX, args []InsertDeploymentResourceParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertDeploymentResource, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.DeploymentID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.Name)
		allArgs = append(allArgs, arg.Kind)
		allArgs = append(allArgs, arg.K8sName)
		allArgs = append(allArgs, arg.Image)
		allArgs = append(allArgs, arg.Command)
		allArgs = append(allArgs, arg.Port)
		allArgs = append(allArgs, arg.UpstreamProtocol)
		allArgs = append(allArgs, arg.Public)
		allArgs = append(allArgs, arg.Schedule)
		allArgs = append(allArgs, arg.Runtime)
		allArgs = append(allArgs, arg.Handler)
		allArgs = append(allArgs, arg.Bindings)
		allArgs = append(allArgs, arg.AllowedCallers)
		allArgs = append(allArgs, arg.CpuMillicores)
		allArgs = append(allArgs, arg.MemoryMib)
		allArgs = append(allArgs, arg.StorageMib)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
