// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertDeploymentManifest is the base query for bulk insert
const bulkInsertDeploymentManifest = `INSERT INTO deployment_manifests ( deployment_id, workspace_id, project_id, app_id, environment_id, schema_version, fingerprint, adapter_id, output_mode, manifest, created_at ) VALUES %s`

// InsertDeploymentManifests performs bulk insert in a single query
func (q *BulkQueries) InsertDeploymentManifests(ctx context.Context, db DBTX, args []InsertDeploymentManifestParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertDeploymentManifest, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.DeploymentID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.SchemaVersion)
		allArgs = append(allArgs, arg.Fingerprint)
		allArgs = append(allArgs, arg.AdapterID)
		allArgs = append(allArgs, arg.OutputMode)
		allArgs = append(allArgs, arg.Manifest)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
