// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_list.sql

package db

import (
	"context"
)

const listDeploymentTargetAssignmentsByEnvironment = `-- name: ListDeploymentTargetAssignmentsByEnvironment :many
SELECT pk, id, target_id, workspace_id, project_id, app_id, environment_id, deployment_id, previous_deployment_id, reason, operation_id, created_at
FROM deployment_target_assignments
WHERE environment_id = ?
ORDER BY created_at DESC, pk DESC
`

// ListDeploymentTargetAssignmentsByEnvironment
//
//	SELECT pk, id, target_id, workspace_id, project_id, app_id, environment_id, deployment_id, previous_deployment_id, reason, operation_id, created_at
//	FROM deployment_target_assignments
//	WHERE environment_id = ?
//	ORDER BY created_at DESC, pk DESC
func (q *Queries) ListDeploymentTargetAssignmentsByEnvironment(ctx context.Context, db DBTX, environmentID string) ([]DeploymentTargetAssignment, error) {
	rows, err := db.QueryContext(ctx, listDeploymentTargetAssignmentsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentTargetAssignment
	for rows.Next() {
		var i DeploymentTargetAssignment
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.TargetID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.PreviousDeploymentID,
			&i.Reason,
			&i.OperationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentTargetAssignmentsByTarget = `-- name: ListDeploymentTargetAssignmentsByTarget :many
SELECT pk, id, target_id, workspace_id, project_id, app_id, environment_id, deployment_id, previous_deployment_id, reason, operation_id, created_at
FROM deployment_target_assignments
WHERE target_id = ?
ORDER BY created_at DESC, pk DESC
`

// ListDeploymentTargetAssignmentsByTarget
//
//	SELECT pk, id, target_id, workspace_id, project_id, app_id, environment_id, deployment_id, previous_deployment_id, reason, operation_id, created_at
//	FROM deployment_target_assignments
//	WHERE target_id = ?
//	ORDER BY created_at DESC, pk DESC
func (q *Queries) ListDeploymentTargetAssignmentsByTarget(ctx context.Context, db DBTX, targetID string) ([]DeploymentTargetAssignment, error) {
	rows, err := db.QueryContext(ctx, listDeploymentTargetAssignmentsByTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentTargetAssignment
	for rows.Next() {
		var i DeploymentTargetAssignment
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.TargetID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.PreviousDeploymentID,
			&i.Reason,
			&i.OperationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentTargetsByEnvironment = `-- name: ListDeploymentTargetsByEnvironment :many
SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at
FROM deployment_targets
WHERE environment_id = ?
ORDER BY kind ASC, target_key ASC
`

// ListDeploymentTargetsByEnvironment
//
//	SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at
//	FROM deployment_targets
//	WHERE environment_id = ?
//	ORDER BY kind ASC, target_key ASC
func (q *Queries) ListDeploymentTargetsByEnvironment(ctx context.Context, db DBTX, environmentID string) ([]DeploymentTarget, error) {
	rows, err := db.QueryContext(ctx, listDeploymentTargetsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentTarget
	for rows.Next() {
		var i DeploymentTarget
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Kind,
			&i.TargetKey,
			&i.DeploymentID,
			&i.PreviousDeploymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
