// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resource_topology_find.sql

package db

import (
	"context"
	"database/sql"
)

const findDeploymentResourceTopology = `-- name: FindDeploymentResourceTopology :one
SELECT
    dt.pk, dt.workspace_id, dt.deployment_id, dt.resource_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.desired_status, dt.created_at, dt.updated_at,
    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.` + "`" + `trigger` + "`" + `, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at,
    dr.pk, dr.id, dr.deployment_id, dr.workspace_id, dr.project_id, dr.app_id, dr.environment_id, dr.name, dr.kind, dr.k8s_name, dr.image, dr.command, dr.port, dr.upstream_protocol, dr.public, dr.schedule, dr.runtime, dr.handler, dr.bindings, dr.allowed_callers, dr.cpu_millicores, dr.memory_mib, dr.storage_mib, dr.created_at,
    w.k8s_namespace,
    e.slug AS environment_slug,
    r.name AS region_name,
    grc.repository_full_name AS git_repo
FROM deployment_topology dt
INNER JOIN deployments d ON dt.deployment_id = d.id
INNER JOIN deployment_resources dr ON dt.resource_id = dr.id
INNER JOIN workspaces w ON d.workspace_id = w.id
INNER JOIN regions r ON dt.region_id = r.id
INNER JOIN environments e ON d.environment_id = e.id
LEFT JOIN github_repo_connections grc ON d.app_id = grc.app_id
WHERE dt.deployment_id = ?
  AND dt.resource_id = ?
  AND dt.region_id = ?
LIMIT 1
`

type FindDeploymentResourceTopologyParams struct {
	DeploymentID string `db:"deployment_id"`
	ResourceID   string `db:"resource_id"`
	RegionID     string `db:"region_id"`
}

type FindDeploymentResourceTopologyRow struct {
	DeploymentTopology DeploymentTopology `db:"deployment_topology"`
	Deployment         Deployment         `db:"deployment"`
	DeploymentResource DeploymentResource `db:"deployment_resource"`
	K8sNamespace       sql.NullString     `db:"k8s_namespace"`
	EnvironmentSlug    string             `db:"environment_slug"`
	RegionName         string             `db:"region_name"`
	GitRepo            sql.NullString     `db:"git_repo"`
}

// FindDeploymentResourceTopology
//
//	SELECT
//	    dt.pk, dt.workspace_id, dt.deployment_id, dt.resource_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.desired_status, dt.created_at, dt.updated_at,
//	    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.`trigger`, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at,
//	    dr.pk, dr.id, dr.deployment_id, dr.workspace_id, dr.project_id, dr.app_id, dr.environment_id, dr.name, dr.kind, dr.k8s_name, dr.image, dr.command, dr.port, dr.upstream_protocol, dr.public, dr.schedule, dr.runtime, dr.handler, dr.bindings, dr.allowed_callers, dr.cpu_millicores, dr.memory_mib, dr.storage_mib, dr.created_at,
//	    w.k8s_namespace,
//	    e.slug AS environment_slug,
//	    r.name AS region_name,
//	    grc.repository_full_name AS git_repo
//	FROM deployment_topology dt
//	INNER JOIN deployments d ON dt.deployment_id = d.id
//	INNER JOIN deployment_resources dr ON dt.resource_id = dr.id
//	INNER JOIN workspaces w ON d.workspace_id = w.id
//	INNER JOIN regions r ON dt.region_id = r.id
//	INNER JOIN environments e ON d.environment_id = e.id
//	LEFT JOIN github_repo_connections grc ON d.app_id = grc.app_id
//	WHERE dt.deployment_id = ?
//	  AND dt.resource_id = ?
//	  AND dt.region_id = ?
//	LIMIT 1
func (q *Queries) FindDeploymentResourceTopology(ctx context.Context, db DBTX, arg FindDeploymentResourceTopologyParams) (FindDeploymentResourceTopologyRow, error) {
	row := db.QueryRowContext(ctx, findDeploymentResourceTopology, arg.DeploymentID, arg.ResourceID, arg.RegionID)
	var i FindDeploymentResourceTopologyRow
	err := row.Scan(
		&i.DeploymentTopology.Pk,
		&i.DeploymentTopology.WorkspaceID,
		&i.DeploymentTopology.DeploymentID,
		&i.DeploymentTopology.ResourceID,
		&i.DeploymentTopology.RegionID,
		&i.DeploymentTopology.AutoscalingReplicasMin,
		&i.DeploymentTopology.AutoscalingReplicasMax,
		&i.DeploymentTopology.AutoscalingThresholdCpu,
		&i.DeploymentTopology.AutoscalingThresholdMemory,
		&i.DeploymentTopology.DesiredStatus,
		&i.DeploymentTopology.CreatedAt,
		&i.DeploymentTopology.UpdatedAt,
		&i.Deployment.Pk,
		&i.Deployment.ID,
		&i.Deployment.K8sName,
		&i.Deployment.WorkspaceID,
		&i.Deployment.ProjectID,
		&i.Deployment.EnvironmentID,
		&i.Deployment.AppID,
		&i.Deployment.Image,
		&i.Deployment.BuildID,
		&i.Deployment.GitCommitSha,
		&i.Deployment.GitBranch,
		&i.Deployment.GitCommitMessage,
		&i.Deployment.GitCommitAuthorHandle,
		&i.Deployment.GitCommitAuthorAvatarUrl,
		&i.Deployment.GitCommitTimestamp,
		&i.Deployment.SentinelConfig,
		&i.Deployment.CpuMillicores,
		&i.Deployment.MemoryMib,
		&i.Deployment.StorageMib,
		&i.Deployment.DesiredState,
		&i.Deployment.EncryptedEnvironmentVariables,
		&i.Deployment.Command,
		&i.Deployment.Port,
		&i.Deployment.ShutdownSignal,
		&i.Deployment.UpstreamProtocol,
		&i.Deployment.Healthcheck,
		&i.Deployment.PrNumber,
		&i.Deployment.ForkRepositoryFullName,
		&i.Deployment.GithubDeploymentID,
		&i.Deployment.InvocationID,
		&i.Deployment.Status,
		&i.Deployment.Trigger,
		&i.Deployment.TriggeredBy,
		&i.Deployment.TriggerReason,
		&i.Deployment.CreatedAt,
		&i.Deployment.UpdatedAt,
		&i.DeploymentResource.Pk,
		&i.DeploymentResource.ID,
		&i.DeploymentResource.DeploymentID,
		&i.DeploymentResource.WorkspaceID,
		&i.DeploymentResource.ProjectID,
		&i.DeploymentResource.AppID,
		&i.DeploymentResource.EnvironmentID,
		&i.DeploymentResource.Name,
		&i.DeploymentResource.Kind,
		&i.DeploymentResource.K8sName,
		&i.DeploymentResource.Image,
		&i.DeploymentResource.Command,
		&i.DeploymentResource.Port,
		&i.DeploymentResource.UpstreamProtocol,
		&i.DeploymentResource.Public,
		&i.DeploymentResource.Schedule,
		&i.DeploymentResource.Runtime,
		&i.DeploymentResource.Handler,
		&i.DeploymentResource.Bindings,
		&i.DeploymentResource.AllowedCallers,
		&i.DeploymentResource.CpuMillicores,
		&i.DeploymentResource.MemoryMib,
		&i.DeploymentResource.StorageMib,
		&i.DeploymentResource.CreatedAt,
		&i.K8sNamespace,
		&i.EnvironmentSlug,
		&i.RegionName,
		&i.GitRepo,
	)
	return i, err
}

const listDeploymentResourceTopologiesByRegion = `-- name: ListDeploymentResourceTopologiesByRegion :many
SELECT
    dt.pk, dt.workspace_id, dt.deployment_id, dt.resource_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.desired_status, dt.created_at, dt.updated_at,
    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.` + "`" + `trigger` + "`" + `, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at,
    dr.pk, dr.id, dr.deployment_id, dr.workspace_id, dr.project_id, dr.app_id, dr.environment_id, dr.name, dr.kind, dr.k8s_name, dr.image, dr.command, dr.port, dr.upstream_protocol, dr.public, dr.schedule, dr.runtime, dr.handler, dr.bindings, dr.allowed_callers, dr.cpu_millicores, dr.memory_mib, dr.storage_mib, dr.created_at,
    w.k8s_namespace,
    e.slug AS environment_slug,
    r.name AS region_name,
    grc.repository_full_name AS git_repo
FROM deployment_topology dt
INNER JOIN deployments d ON dt.deployment_id = d.id
INNER JOIN deployment_resources dr ON dt.resource_id = dr.id
INNER JOIN workspaces w ON d.workspace_id = w.id
INNER JOIN regions r ON dt.region_id = r.id
INNER JOIN environments e ON d.environment_id = e.id
LEFT JOIN github_repo_connections grc ON d.app_id = grc.app_id
WHERE r.id = ?
  AND dt.pk > ?
  AND dt.desired_status = 'running'
  AND dt.resource_id != ''
ORDER BY dt.pk ASC
LIMIT ?
`

type ListDeploymentResourceTopologiesByRegionParams struct {
	RegionID string `db:"region_id"`
	AfterPk  uint64 `db:"after_pk"`
	Limit    int32  `db:"limit"`
}

type ListDeploymentResourceTopologiesByRegionRow struct {
	DeploymentTopology DeploymentTopology `db:"deployment_topology"`
	Deployment         Deployment         `db:"deployment"`
	DeploymentResource DeploymentResource `db:"deployment_resource"`
	K8sNamespace       sql.NullString     `db:"k8s_namespace"`
	EnvironmentSlug    string             `db:"environment_slug"`
	RegionName         string             `db:"region_name"`
	GitRepo            sql.NullString     `db:"git_repo"`
}

// ListDeploymentResourceTopologiesByRegion
//
//	SELECT
//	    dt.pk, dt.workspace_id, dt.deployment_id, dt.resource_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.desired_status, dt.created_at, dt.updated_at,
//	    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.`trigger`, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at,
//	    dr.pk, dr.id, dr.deployment_id, dr.workspace_id, dr.project_id, dr.app_id, dr.environment_id, dr.name, dr.kind, dr.k8s_name, dr.image, dr.command, dr.port, dr.upstream_protocol, dr.public, dr.schedule, dr.runtime, dr.handler, dr.bindings, dr.allowed_callers, dr.cpu_millicores, dr.memory_mib, dr.storage_mib, dr.created_at,
//	    w.k8s_namespace,
//	    e.slug AS environment_slug,
//	    r.name AS region_name,
//	    grc.repository_full_name AS git_repo
//	FROM deployment_topology dt
//	INNER JOIN deployments d ON dt.deployment_id = d.id
//	INNER JOIN deployment_resources dr ON dt.resource_id = dr.id
//	INNER JOIN workspaces w ON d.workspace_id = w.id
//	INNER JOIN regions r ON dt.region_id = r.id
//	INNER JOIN environments e ON d.environment_id = e.id
//	LEFT JOIN github_repo_connections grc ON d.app_id = grc.app_id
//	WHERE r.id = ?
//	  AND dt.pk > ?
//	  AND dt.desired_status = 'running'
//	  AND dt.resource_id != ''
//	ORDER BY dt.pk ASC
//	LIMIT ?
func (q *Queries) ListDeploymentResourceTopologiesByRegion(ctx context.Context, db DBTX, arg ListDeploymentResourceTopologiesByRegionParams) ([]ListDeploymentResourceTopologiesByRegionRow, error) {
	rows, err := db.QueryContext(ctx, listDeploymentResourceTopologiesByRegion, arg.RegionID, arg.AfterPk, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentResourceTopologiesByRegionRow
	for rows.Next() {
		var i ListDeploymentResourceTopologiesByRegionRow
		if err := rows.Scan(
			&i.DeploymentTopology.Pk,
			&i.DeploymentTopology.WorkspaceID,
			&i.DeploymentTopology.DeploymentID,
			&i.DeploymentTopology.ResourceID,
			&i.DeploymentTopology.RegionID,
			&i.DeploymentTopology.AutoscalingReplicasMin,
			&i.DeploymentTopology.AutoscalingReplicasMax,
			&i.DeploymentTopology.AutoscalingThresholdCpu,
			&i.DeploymentTopology.AutoscalingThresholdMemory,
			&i.DeploymentTopology.DesiredStatus,
			&i.DeploymentTopology.CreatedAt,
			&i.DeploymentTopology.UpdatedAt,
			&i.Deployment.Pk,
			&i.Deployment.ID,
			&i.Deployment.K8sName,
			&i.Deployment.WorkspaceID,
			&i.Deployment.ProjectID,
			&i.Deployment.EnvironmentID,
			&i.Deployment.AppID,
			&i.Deployment.Image,
			&i.Deployment.BuildID,
			&i.Deployment.GitCommitSha,
			&i.Deployment.GitBranch,
			&i.Deployment.GitCommitMessage,
			&i.Deployment.GitCommitAuthorHandle,
			&i.Deployment.GitCommitAuthorAvatarUrl,
			&i.Deployment.GitCommitTimestamp,
			&i.Deployment.SentinelConfig,
			&i.Deployment.CpuMillicores,
			&i.Deployment.MemoryMib,
			&i.Deployment.StorageMib,
			&i.Deployment.DesiredState,
			&i.Deployment.EncryptedEnvironmentVariables,
			&i.Deployment.Command,
			&i.Deployment.Port,
			&i.Deployment.ShutdownSignal,
			&i.Deployment.UpstreamProtocol,
			&i.Deployment.Healthcheck,
			&i.Deployment.PrNumber,
			&i.Deployment.ForkRepositoryFullName,
			&i.Deployment.GithubDeploymentID,
			&i.Deployment.InvocationID,
			&i.Deployment.Status,
			&i.Deployment.Trigger,
			&i.Deployment.TriggeredBy,
			&i.Deployment.TriggerReason,
			&i.Deployment.CreatedAt,
			&i.Deployment.UpdatedAt,
			&i.DeploymentResource.Pk,
			&i.DeploymentResource.ID,
			&i.DeploymentResource.DeploymentID,
			&i.DeploymentResource.WorkspaceID,
			&i.DeploymentResource.ProjectID,
			&i.DeploymentResource.AppID,
			&i.DeploymentResource.EnvironmentID,
			&i.DeploymentResource.Name,
			&i.DeploymentResource.Kind,
			&i.DeploymentResource.K8sName,
			&i.DeploymentResource.Image,
			&i.DeploymentResource.Command,
			&i.DeploymentResource.Port,
			&i.DeploymentResource.UpstreamProtocol,
			&i.DeploymentResource.Public,
			&i.DeploymentResource.Schedule,
			&i.DeploymentResource.Runtime,
			&i.DeploymentResource.Handler,
			&i.DeploymentResource.Bindings,
			&i.DeploymentResource.AllowedCallers,
			&i.DeploymentResource.CpuMillicores,
			&i.DeploymentResource.MemoryMib,
			&i.DeploymentResource.StorageMib,
			&i.DeploymentResource.CreatedAt,
			&i.K8sNamespace,
			&i.EnvironmentSlug,
			&i.RegionName,
			&i.GitRepo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
