// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_min_replicas_by_deployment.sql

package db

import (
	"context"
)

const findDeploymentTopologyMinReplicas = `-- name: FindDeploymentTopologyMinReplicas :many
SELECT resource_id, region_id, autoscaling_replicas_min
FROM deployment_topology
WHERE deployment_id = ?
`

type FindDeploymentTopologyMinReplicasRow struct {
	ResourceID             string `db:"resource_id"`
	RegionID               string `db:"region_id"`
	AutoscalingReplicasMin uint32 `db:"autoscaling_replicas_min"`
}

// Returns the per-region minimum replica requirement for a deployment.
// Used by deploy and wake workflows to compute whether enough regions are
// healthy before a deployment is considered ready.
//
//	SELECT resource_id, region_id, autoscaling_replicas_min
//	FROM deployment_topology
//	WHERE deployment_id = ?
func (q *Queries) FindDeploymentTopologyMinReplicas(ctx context.Context, db DBTX, deploymentID string) ([]FindDeploymentTopologyMinReplicasRow, error) {
	rows, err := db.QueryContext(ctx, findDeploymentTopologyMinReplicas, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDeploymentTopologyMinReplicasRow
	for rows.Next() {
		var i FindDeploymentTopologyMinReplicasRow
		if err := rows.Scan(&i.ResourceID, &i.RegionID, &i.AutoscalingReplicasMin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
