// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_find.sql

package db

import (
	"context"
)

const findDeploymentTargetByID = `-- name: FindDeploymentTargetByID :one
SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at FROM deployment_targets WHERE id = ?
`

// FindDeploymentTargetByID
//
//	SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at FROM deployment_targets WHERE id = ?
func (q *Queries) FindDeploymentTargetByID(ctx context.Context, db DBTX, id string) (DeploymentTarget, error) {
	row := db.QueryRowContext(ctx, findDeploymentTargetByID, id)
	var i DeploymentTarget
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Kind,
		&i.TargetKey,
		&i.DeploymentID,
		&i.PreviousDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDeploymentTargetByIdentity = `-- name: FindDeploymentTargetByIdentity :one
SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at
FROM deployment_targets
WHERE app_id = ?
  AND environment_id = ?
  AND kind = ?
  AND target_key = ?
`

type FindDeploymentTargetByIdentityParams struct {
	AppID         string                `db:"app_id"`
	EnvironmentID string                `db:"environment_id"`
	Kind          DeploymentTargetsKind `db:"kind"`
	TargetKey     string                `db:"target_key"`
}

// FindDeploymentTargetByIdentity
//
//	SELECT pk, id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at
//	FROM deployment_targets
//	WHERE app_id = ?
//	  AND environment_id = ?
//	  AND kind = ?
//	  AND target_key = ?
func (q *Queries) FindDeploymentTargetByIdentity(ctx context.Context, db DBTX, arg FindDeploymentTargetByIdentityParams) (DeploymentTarget, error) {
	row := db.QueryRowContext(ctx, findDeploymentTargetByIdentity,
		arg.AppID,
		arg.EnvironmentID,
		arg.Kind,
		arg.TargetKey,
	)
	var i DeploymentTarget
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Kind,
		&i.TargetKey,
		&i.DeploymentID,
		&i.PreviousDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
