// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_delete_by_environment.sql

package db

import (
	"context"
)

const deleteDeploymentTargetAssignmentsByEnvironment = `-- name: DeleteDeploymentTargetAssignmentsByEnvironment :exec
DELETE FROM deployment_target_assignments WHERE environment_id = ?
`

// DeleteDeploymentTargetAssignmentsByEnvironment
//
//	DELETE FROM deployment_target_assignments WHERE environment_id = ?
func (q *Queries) DeleteDeploymentTargetAssignmentsByEnvironment(ctx context.Context, db DBTX, environmentID string) error {
	_, err := db.ExecContext(ctx, deleteDeploymentTargetAssignmentsByEnvironment, environmentID)
	return err
}

const deleteDeploymentTargetsByEnvironment = `-- name: DeleteDeploymentTargetsByEnvironment :exec
DELETE FROM deployment_targets WHERE environment_id = ?
`

// DeleteDeploymentTargetsByEnvironment
//
//	DELETE FROM deployment_targets WHERE environment_id = ?
func (q *Queries) DeleteDeploymentTargetsByEnvironment(ctx context.Context, db DBTX, environmentID string) error {
	_, err := db.ExecContext(ctx, deleteDeploymentTargetsByEnvironment, environmentID)
	return err
}
