// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_artifact_find.sql

package db

import (
	"context"
)

const findDeploymentArtifact = `-- name: FindDeploymentArtifact :one
SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, storage_key, digest, size_bytes, content_type, metadata, created_at
FROM deployment_artifacts
WHERE deployment_id = ?
  AND kind = ?
  AND name = ?
`

type FindDeploymentArtifactParams struct {
	DeploymentID string                  `db:"deployment_id"`
	Kind         DeploymentArtifactsKind `db:"kind"`
	Name         string                  `db:"name"`
}

// FindDeploymentArtifact
//
//	SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, storage_key, digest, size_bytes, content_type, metadata, created_at
//	FROM deployment_artifacts
//	WHERE deployment_id = ?
//	  AND kind = ?
//	  AND name = ?
func (q *Queries) FindDeploymentArtifact(ctx context.Context, db DBTX, arg FindDeploymentArtifactParams) (DeploymentArtifact, error) {
	row := db.QueryRowContext(ctx, findDeploymentArtifact, arg.DeploymentID, arg.Kind, arg.Name)
	var i DeploymentArtifact
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Name,
		&i.Kind,
		&i.StorageKey,
		&i.Digest,
		&i.SizeBytes,
		&i.ContentType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
