// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_artifact_list.sql

package db

import (
	"context"
)

const listDeploymentArtifacts = `-- name: ListDeploymentArtifacts :many
SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, storage_key, digest, size_bytes, content_type, metadata, created_at
FROM deployment_artifacts
WHERE deployment_id = ?
ORDER BY created_at ASC, name ASC
`

// ListDeploymentArtifacts
//
//	SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, storage_key, digest, size_bytes, content_type, metadata, created_at
//	FROM deployment_artifacts
//	WHERE deployment_id = ?
//	ORDER BY created_at ASC, name ASC
func (q *Queries) ListDeploymentArtifacts(ctx context.Context, db DBTX, deploymentID string) ([]DeploymentArtifact, error) {
	rows, err := db.QueryContext(ctx, listDeploymentArtifacts, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentArtifact
	for rows.Next() {
		var i DeploymentArtifact
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.DeploymentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Name,
			&i.Kind,
			&i.StorageKey,
			&i.Digest,
			&i.SizeBytes,
			&i.ContentType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
