// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frontline_route_revision_bump.sql

package db

import (
	"context"
)

const bumpFrontlineRouteRevision = `-- name: BumpFrontlineRouteRevision :exec
INSERT INTO frontline_route_revisions (id, revision)
VALUES (1, 1)
ON DUPLICATE KEY UPDATE revision = revision + 1
`

// BumpFrontlineRouteRevision
//
//	INSERT INTO frontline_route_revisions (id, revision)
//	VALUES (1, 1)
//	ON DUPLICATE KEY UPDATE revision = revision + 1
func (q *Queries) BumpFrontlineRouteRevision(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, bumpFrontlineRouteRevision)
	return err
}
