// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_target.sql

package db

import (
	"context"
	"database/sql"
)

const findFrontlineRouteByID = `-- name: FindFrontlineRouteByID :one
SELECT pk, id, project_id, app_id, deployment_id, target_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at FROM frontline_routes WHERE id = ?
`

// FindFrontlineRouteByID
//
//	SELECT pk, id, project_id, app_id, deployment_id, target_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at FROM frontline_routes WHERE id = ?
func (q *Queries) FindFrontlineRouteByID(ctx context.Context, db DBTX, id string) (FrontlineRoute, error) {
	row := db.QueryRowContext(ctx, findFrontlineRouteByID, id)
	var i FrontlineRoute
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ProjectID,
		&i.AppID,
		&i.DeploymentID,
		&i.TargetID,
		&i.EnvironmentID,
		&i.FullyQualifiedDomainName,
		&i.Sticky,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkFrontlineRouteTarget = `-- name: LinkFrontlineRouteTarget :exec
UPDATE frontline_routes
SET
  target_id = ?,
  updated_at = ?
WHERE id = ?
`

type LinkFrontlineRouteTargetParams struct {
	TargetID  sql.NullString `db:"target_id"`
	UpdatedAt sql.NullInt64  `db:"updated_at"`
	ID        string         `db:"id"`
}

// LinkFrontlineRouteTarget
//
//	UPDATE frontline_routes
//	SET
//	  target_id = ?,
//	  updated_at = ?
//	WHERE id = ?
func (q *Queries) LinkFrontlineRouteTarget(ctx context.Context, db DBTX, arg LinkFrontlineRouteTargetParams) error {
	_, err := db.ExecContext(ctx, linkFrontlineRouteTarget, arg.TargetID, arg.UpdatedAt, arg.ID)
	return err
}
