// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances_find_by_resource_and_region.sql

package db

import (
	"context"
)

const deleteResourceInstances = `-- name: DeleteResourceInstances :exec
DELETE FROM instances
WHERE resource_id = ?
  AND region_id = ?
`

type DeleteResourceInstancesParams struct {
	ResourceID string `db:"resource_id"`
	RegionID   string `db:"region_id"`
}

// DeleteResourceInstances
//
//	DELETE FROM instances
//	WHERE resource_id = ?
//	  AND region_id = ?
func (q *Queries) DeleteResourceInstances(ctx context.Context, db DBTX, arg DeleteResourceInstancesParams) error {
	_, err := db.ExecContext(ctx, deleteResourceInstances, arg.ResourceID, arg.RegionID)
	return err
}

const findInstancesByResourceAndRegion = `-- name: FindInstancesByResourceAndRegion :many
SELECT pk, id, deployment_id, resource_id, workspace_id, project_id, app_id, region_id, k8s_name, address, cpu_millicores, memory_mib, storage_mib, status, container_status
FROM instances
WHERE resource_id = ?
  AND region_id = ?
`

type FindInstancesByResourceAndRegionParams struct {
	ResourceID string `db:"resource_id"`
	RegionID   string `db:"region_id"`
}

// FindInstancesByResourceAndRegion
//
//	SELECT pk, id, deployment_id, resource_id, workspace_id, project_id, app_id, region_id, k8s_name, address, cpu_millicores, memory_mib, storage_mib, status, container_status
//	FROM instances
//	WHERE resource_id = ?
//	  AND region_id = ?
func (q *Queries) FindInstancesByResourceAndRegion(ctx context.Context, db DBTX, arg FindInstancesByResourceAndRegionParams) ([]Instance, error) {
	rows, err := db.QueryContext(ctx, findInstancesByResourceAndRegion, arg.ResourceID, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.DeploymentID,
			&i.ResourceID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.RegionID,
			&i.K8sName,
			&i.Address,
			&i.CpuMillicores,
			&i.MemoryMib,
			&i.StorageMib,
			&i.Status,
			&i.ContainerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
