// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_billing_settings_list_stripe_connected.sql

package db

import (
	"context"
)

const listStripeConnectedWorkspaces = `-- name: ListStripeConnectedWorkspaces :many
SELECT pk, id, workspace_id, default_rate_card_id, stripe_connect_encrypted, stripe_connect_encryption_key_id, created_at, updated_at
FROM workspace_billing_settings
WHERE stripe_connect_encrypted IS NOT NULL
ORDER BY pk
LIMIT ? OFFSET ?
`

type ListStripeConnectedWorkspacesParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

// ListStripeConnectedWorkspaces
//
//	SELECT pk, id, workspace_id, default_rate_card_id, stripe_connect_encrypted, stripe_connect_encryption_key_id, created_at, updated_at
//	FROM workspace_billing_settings
//	WHERE stripe_connect_encrypted IS NOT NULL
//	ORDER BY pk
//	LIMIT ? OFFSET ?
func (q *Queries) ListStripeConnectedWorkspaces(ctx context.Context, db DBTX, arg ListStripeConnectedWorkspacesParams) ([]WorkspaceBillingSetting, error) {
	rows, err := db.QueryContext(ctx, listStripeConnectedWorkspaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceBillingSetting
	for rows.Next() {
		var i WorkspaceBillingSetting
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.WorkspaceID,
			&i.DefaultRateCardID,
			&i.StripeConnectEncrypted,
			&i.StripeConnectEncryptionKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
