// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_regional_settings_insert_with_policy.sql

package db

import (
	"context"
	"database/sql"
)

const insertAppRegionalSettingsWithPolicy = `-- name: InsertAppRegionalSettingsWithPolicy :exec
INSERT INTO app_regional_settings (
    workspace_id,
    app_id,
    environment_id,
    region_id,
    replicas,
    horizontal_autoscaling_policy_id,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertAppRegionalSettingsWithPolicyParams struct {
	WorkspaceID                   string         `db:"workspace_id"`
	AppID                         string         `db:"app_id"`
	EnvironmentID                 string         `db:"environment_id"`
	RegionID                      string         `db:"region_id"`
	Replicas                      int32          `db:"replicas"`
	HorizontalAutoscalingPolicyID sql.NullString `db:"horizontal_autoscaling_policy_id"`
	CreatedAt                     int64          `db:"created_at"`
	UpdatedAt                     sql.NullInt64  `db:"updated_at"`
}

// InsertAppRegionalSettingsWithPolicy
//
//	INSERT INTO app_regional_settings (
//	    workspace_id,
//	    app_id,
//	    environment_id,
//	    region_id,
//	    replicas,
//	    horizontal_autoscaling_policy_id,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertAppRegionalSettingsWithPolicy(ctx context.Context, arg InsertAppRegionalSettingsWithPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertAppRegionalSettingsWithPolicy,
		arg.WorkspaceID,
		arg.AppID,
		arg.EnvironmentID,
		arg.RegionID,
		arg.Replicas,
		arg.HorizontalAutoscalingPolicyID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
