// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_framework_detection_find_applied.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const findAppliedFrameworkDetection = `-- name: FindAppliedFrameworkDetection :one
SELECT
    fingerprint,
    detection_version,
    detected_preset_id,
    detection,
    defaults
FROM app_framework_detections
WHERE workspace_id = ?
  AND project_id = ?
  AND app_id = ?
  AND applied_fingerprint = fingerprint
LIMIT 1
`

type FindAppliedFrameworkDetectionParams struct {
	WorkspaceID string `db:"workspace_id"`
	ProjectID   string `db:"project_id"`
	AppID       string `db:"app_id"`
}

type FindAppliedFrameworkDetectionRow struct {
	Fingerprint      string          `db:"fingerprint"`
	DetectionVersion uint64          `db:"detection_version"`
	DetectedPresetID sql.NullString  `db:"detected_preset_id"`
	Detection        json.RawMessage `db:"detection"`
	Defaults         json.RawMessage `db:"defaults"`
}

// FindAppliedFrameworkDetection
//
//	SELECT
//	    fingerprint,
//	    detection_version,
//	    detected_preset_id,
//	    detection,
//	    defaults
//	FROM app_framework_detections
//	WHERE workspace_id = ?
//	  AND project_id = ?
//	  AND app_id = ?
//	  AND applied_fingerprint = fingerprint
//	LIMIT 1
func (q *Queries) FindAppliedFrameworkDetection(ctx context.Context, arg FindAppliedFrameworkDetectionParams) (FindAppliedFrameworkDetectionRow, error) {
	row := q.db.QueryRowContext(ctx, findAppliedFrameworkDetection, arg.WorkspaceID, arg.ProjectID, arg.AppID)
	var i FindAppliedFrameworkDetectionRow
	err := row.Scan(
		&i.Fingerprint,
		&i.DetectionVersion,
		&i.DetectedPresetID,
		&i.Detection,
		&i.Defaults,
	)
	return i, err
}
