// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_build_settings_clone.sql

package db

import (
	"context"
	"database/sql"
)

const cloneAppBuildSettings = `-- name: CloneAppBuildSettings :exec
INSERT INTO app_build_settings (
    workspace_id,
    app_id,
    environment_id,
    dockerfile,
    docker_context,
    build_command,
    watch_paths,
    auto_deploy,
    created_at,
    updated_at
)
SELECT
    source.workspace_id,
    source.app_id,
    ?,
    source.dockerfile,
    source.docker_context,
    source.build_command,
    source.watch_paths,
    source.auto_deploy,
    ?,
    ?
FROM app_build_settings AS source
WHERE source.app_id = ?
    AND source.environment_id = ?
`

type CloneAppBuildSettingsParams struct {
	TargetEnvironmentID string        `db:"target_environment_id"`
	CreatedAt           int64         `db:"created_at"`
	UpdatedAt           sql.NullInt64 `db:"updated_at"`
	AppID               string        `db:"app_id"`
	SourceEnvironmentID string        `db:"source_environment_id"`
}

// CloneAppBuildSettings
//
//	INSERT INTO app_build_settings (
//	    workspace_id,
//	    app_id,
//	    environment_id,
//	    dockerfile,
//	    docker_context,
//	    build_command,
//	    watch_paths,
//	    auto_deploy,
//	    created_at,
//	    updated_at
//	)
//	SELECT
//	    source.workspace_id,
//	    source.app_id,
//	    ?,
//	    source.dockerfile,
//	    source.docker_context,
//	    source.build_command,
//	    source.watch_paths,
//	    source.auto_deploy,
//	    ?,
//	    ?
//	FROM app_build_settings AS source
//	WHERE source.app_id = ?
//	    AND source.environment_id = ?
func (q *Queries) CloneAppBuildSettings(ctx context.Context, arg CloneAppBuildSettingsParams) error {
	_, err := q.db.ExecContext(ctx, cloneAppBuildSettings,
		arg.TargetEnvironmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AppID,
		arg.SourceEnvironmentID,
	)
	return err
}
