// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_runtime_settings_clone.sql

package db

import (
	"context"
	"database/sql"
)

const cloneAppRuntimeSettings = `-- name: CloneAppRuntimeSettings :exec
INSERT INTO app_runtime_settings (
    workspace_id,
    app_id,
    environment_id,
    port,
    cpu_millicores,
    memory_mib,
    storage_mib,
    command,
    outputs,
    healthcheck,
    shutdown_signal,
    upstream_protocol,
    sentinel_config,
    openapi_spec_path,
    created_at,
    updated_at
)
SELECT
    source.workspace_id,
    source.app_id,
    ?,
    source.port,
    source.cpu_millicores,
    source.memory_mib,
    source.storage_mib,
    source.command,
    source.outputs,
    source.healthcheck,
    source.shutdown_signal,
    source.upstream_protocol,
    source.sentinel_config,
    source.openapi_spec_path,
    ?,
    ?
FROM app_runtime_settings AS source
WHERE source.app_id = ?
    AND source.environment_id = ?
`

type CloneAppRuntimeSettingsParams struct {
	TargetEnvironmentID string        `db:"target_environment_id"`
	CreatedAt           int64         `db:"created_at"`
	UpdatedAt           sql.NullInt64 `db:"updated_at"`
	AppID               string        `db:"app_id"`
	SourceEnvironmentID string        `db:"source_environment_id"`
}

// CloneAppRuntimeSettings
//
//	INSERT INTO app_runtime_settings (
//	    workspace_id,
//	    app_id,
//	    environment_id,
//	    port,
//	    cpu_millicores,
//	    memory_mib,
//	    storage_mib,
//	    command,
//	    outputs,
//	    healthcheck,
//	    shutdown_signal,
//	    upstream_protocol,
//	    sentinel_config,
//	    openapi_spec_path,
//	    created_at,
//	    updated_at
//	)
//	SELECT
//	    source.workspace_id,
//	    source.app_id,
//	    ?,
//	    source.port,
//	    source.cpu_millicores,
//	    source.memory_mib,
//	    source.storage_mib,
//	    source.command,
//	    source.outputs,
//	    source.healthcheck,
//	    source.shutdown_signal,
//	    source.upstream_protocol,
//	    source.sentinel_config,
//	    source.openapi_spec_path,
//	    ?,
//	    ?
//	FROM app_runtime_settings AS source
//	WHERE source.app_id = ?
//	    AND source.environment_id = ?
func (q *Queries) CloneAppRuntimeSettings(ctx context.Context, arg CloneAppRuntimeSettingsParams) error {
	_, err := q.db.ExecContext(ctx, cloneAppRuntimeSettings,
		arg.TargetEnvironmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AppID,
		arg.SourceEnvironmentID,
	)
	return err
}
