// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkRecordDeploymentArtifact is the base query for bulk insert
const bulkRecordDeploymentArtifact = `INSERT INTO deployment_artifacts ( id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, storage_key, digest, size_bytes, content_type, metadata, created_at ) VALUES %s ON DUPLICATE KEY UPDATE id = deployment_artifacts.id`

// RecordDeploymentArtifact performs bulk insert in a single query

func (q *BulkQueries) RecordDeploymentArtifact(ctx context.Context, args []RecordDeploymentArtifactParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkRecordDeploymentArtifact, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.DeploymentID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.Name)
		allArgs = append(allArgs, arg.Kind)
		allArgs = append(allArgs, arg.StorageKey)
		allArgs = append(allArgs, arg.Digest)
		allArgs = append(allArgs, arg.SizeBytes)
		allArgs = append(allArgs, arg.ContentType)
		allArgs = append(allArgs, arg.Metadata)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
