// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertAppRegionalSettingsWithPolicy is the base query for bulk insert
const bulkInsertAppRegionalSettingsWithPolicy = `INSERT INTO app_regional_settings ( workspace_id, app_id, environment_id, region_id, replicas, horizontal_autoscaling_policy_id, created_at, updated_at ) VALUES %s`

// InsertAppRegionalSettingsWithPolicies performs bulk insert in a single query

func (q *BulkQueries) InsertAppRegionalSettingsWithPolicies(ctx context.Context, args []InsertAppRegionalSettingsWithPolicyParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertAppRegionalSettingsWithPolicy, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.RegionID)
		allArgs = append(allArgs, arg.Replicas)
		allArgs = append(allArgs, arg.HorizontalAutoscalingPolicyID)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
