// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertDeploymentTarget is the base query for bulk insert
const bulkInsertDeploymentTarget = `INSERT INTO deployment_targets ( id, workspace_id, project_id, app_id, environment_id, kind, target_key, deployment_id, previous_deployment_id, created_at, updated_at ) VALUES %s ON DUPLICATE KEY UPDATE id = id`

// InsertDeploymentTargets performs bulk insert in a single query

func (q *BulkQueries) InsertDeploymentTargets(ctx context.Context, args []InsertDeploymentTargetParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertDeploymentTarget, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.Kind)
		allArgs = append(allArgs, arg.TargetKey)
		allArgs = append(allArgs, arg.DeploymentID)
		allArgs = append(allArgs, arg.PreviousDeploymentID)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
