// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkCloneAppRuntimeSettings is the base query for bulk insert
const bulkCloneAppRuntimeSettings = `INSERT INTO app_runtime_settings ( workspace_id, app_id, environment_id, port, cpu_millicores, memory_mib, storage_mib, command, outputs, healthcheck, shutdown_signal, upstream_protocol, sentinel_config, openapi_spec_path, created_at, updated_at ) SELECT source.workspace_id, source.app_id, ?, source.port, source.cpu_millicores, source.memory_mib, source.storage_mib, source.command, source.outputs, source.healthcheck, source.shutdown_signal, source.upstream_protocol, source.sentinel_config, source.openapi_spec_path, ?, ? FROM app_runtime_settings AS source WHERE source.app_id = ? AND source.environment_id = ? VALUES %s`

// CloneAppRuntimeSettings performs bulk insert in a single query

func (q *BulkQueries) CloneAppRuntimeSettings(ctx context.Context, args []CloneAppRuntimeSettingsParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "()"
	}

	bulkQuery := fmt.Sprintf(bulkCloneAppRuntimeSettings, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.TargetEnvironmentID)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.SourceEnvironmentID)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
