// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkCloneAppBuildSettings is the base query for bulk insert
const bulkCloneAppBuildSettings = `INSERT INTO app_build_settings ( workspace_id, app_id, environment_id, dockerfile, docker_context, build_command, watch_paths, auto_deploy, created_at, updated_at ) SELECT source.workspace_id, source.app_id, ?, source.dockerfile, source.docker_context, source.build_command, source.watch_paths, source.auto_deploy, ?, ? FROM app_build_settings AS source WHERE source.app_id = ? AND source.environment_id = ? VALUES %s`

// CloneAppBuildSettings performs bulk insert in a single query

func (q *BulkQueries) CloneAppBuildSettings(ctx context.Context, args []CloneAppBuildSettingsParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "()"
	}

	bulkQuery := fmt.Sprintf(bulkCloneAppBuildSettings, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.TargetEnvironmentID)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.SourceEnvironmentID)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
