// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertSlackInstallation is the base query for bulk insert
const bulkInsertSlackInstallation = `INSERT INTO slack_installations ( id, workspace_id, team_id, bot_token, bot_user_id, installed_by_user_id, created_at, updated_at ) VALUES %s`

// InsertSlackInstallations performs bulk insert in a single query

func (q *BulkQueries) InsertSlackInstallations(ctx context.Context, args []InsertSlackInstallationParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertSlackInstallation, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.TeamID)
		allArgs = append(allArgs, arg.BotToken)
		allArgs = append(allArgs, arg.BotUserID)
		allArgs = append(allArgs, arg.InstalledByUserID)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
