// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertHorizontalAutoscalingPolicy is the base query for bulk insert
const bulkInsertHorizontalAutoscalingPolicy = `INSERT INTO horizontal_autoscaling_policies ( id, workspace_id, replicas_min, replicas_max, memory_threshold, cpu_threshold, rps_threshold, created_at, updated_at ) VALUES %s`

// InsertHorizontalAutoscalingPolicies performs bulk insert in a single query

func (q *BulkQueries) InsertHorizontalAutoscalingPolicies(ctx context.Context, args []InsertHorizontalAutoscalingPolicyParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertHorizontalAutoscalingPolicy, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ReplicasMin)
		allArgs = append(allArgs, arg.ReplicasMax)
		allArgs = append(allArgs, arg.MemoryThreshold)
		allArgs = append(allArgs, arg.CpuThreshold)
		allArgs = append(allArgs, arg.RpsThreshold)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
