// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resource_list.sql

package db

import (
	"context"
	"database/sql"
)

const findDeploymentResourceByID = `-- name: FindDeploymentResourceByID :one
SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at FROM deployment_resources WHERE id = ?
`

// FindDeploymentResourceByID
//
//	SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at FROM deployment_resources WHERE id = ?
func (q *Queries) FindDeploymentResourceByID(ctx context.Context, id string) (DeploymentResource, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentResourceByID, id)
	var i DeploymentResource
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Name,
		&i.Kind,
		&i.K8sName,
		&i.Image,
		&i.Command,
		&i.Port,
		&i.UpstreamProtocol,
		&i.Public,
		&i.Schedule,
		&i.Runtime,
		&i.Handler,
		&i.CpuMillicores,
		&i.MemoryMib,
		&i.StorageMib,
		&i.CreatedAt,
	)
	return i, err
}

const findDeploymentResourceByK8sName = `-- name: FindDeploymentResourceByK8sName :one
SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at FROM deployment_resources WHERE k8s_name = ?
`

// FindDeploymentResourceByK8sName
//
//	SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at FROM deployment_resources WHERE k8s_name = ?
func (q *Queries) FindDeploymentResourceByK8sName(ctx context.Context, k8sName sql.NullString) (DeploymentResource, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentResourceByK8sName, k8sName)
	var i DeploymentResource
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Name,
		&i.Kind,
		&i.K8sName,
		&i.Image,
		&i.Command,
		&i.Port,
		&i.UpstreamProtocol,
		&i.Public,
		&i.Schedule,
		&i.Runtime,
		&i.Handler,
		&i.CpuMillicores,
		&i.MemoryMib,
		&i.StorageMib,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentResourcesByDeployment = `-- name: ListDeploymentResourcesByDeployment :many
SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at
FROM deployment_resources
WHERE deployment_id = ?
ORDER BY name ASC
`

// ListDeploymentResourcesByDeployment
//
//	SELECT pk, id, deployment_id, workspace_id, project_id, app_id, environment_id, name, kind, k8s_name, image, command, port, upstream_protocol, public, schedule, runtime, handler, cpu_millicores, memory_mib, storage_mib, created_at
//	FROM deployment_resources
//	WHERE deployment_id = ?
//	ORDER BY name ASC
func (q *Queries) ListDeploymentResourcesByDeployment(ctx context.Context, deploymentID string) ([]DeploymentResource, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentResourcesByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentResource
	for rows.Next() {
		var i DeploymentResource
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.DeploymentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Name,
			&i.Kind,
			&i.K8sName,
			&i.Image,
			&i.Command,
			&i.Port,
			&i.UpstreamProtocol,
			&i.Public,
			&i.Schedule,
			&i.Runtime,
			&i.Handler,
			&i.CpuMillicores,
			&i.MemoryMib,
			&i.StorageMib,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
