// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resource_insert.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertDeploymentResource = `-- name: InsertDeploymentResource :exec
INSERT INTO deployment_resources (
  id,
  deployment_id,
  workspace_id,
  project_id,
  app_id,
  environment_id,
  name,
  kind,
  k8s_name,
  image,
  command,
  port,
  upstream_protocol,
  public,
  schedule,
  runtime,
  handler,
  cpu_millicores,
  memory_mib,
  storage_mib,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE id = id
`

type InsertDeploymentResourceParams struct {
	ID               string                              `db:"id"`
	DeploymentID     string                              `db:"deployment_id"`
	WorkspaceID      string                              `db:"workspace_id"`
	ProjectID        string                              `db:"project_id"`
	AppID            string                              `db:"app_id"`
	EnvironmentID    string                              `db:"environment_id"`
	Name             string                              `db:"name"`
	Kind             DeploymentResourcesKind             `db:"kind"`
	K8sName          sql.NullString                      `db:"k8s_name"`
	Image            sql.NullString                      `db:"image"`
	Command          json.RawMessage                     `db:"command"`
	Port             int32                               `db:"port"`
	UpstreamProtocol DeploymentResourcesUpstreamProtocol `db:"upstream_protocol"`
	Public           bool                                `db:"public"`
	Schedule         sql.NullString                      `db:"schedule"`
	Runtime          sql.NullString                      `db:"runtime"`
	Handler          sql.NullString                      `db:"handler"`
	CpuMillicores    int32                               `db:"cpu_millicores"`
	MemoryMib        int32                               `db:"memory_mib"`
	StorageMib       uint32                              `db:"storage_mib"`
	CreatedAt        int64                               `db:"created_at"`
}

// InsertDeploymentResource
//
//	INSERT INTO deployment_resources (
//	  id,
//	  deployment_id,
//	  workspace_id,
//	  project_id,
//	  app_id,
//	  environment_id,
//	  name,
//	  kind,
//	  k8s_name,
//	  image,
//	  command,
//	  port,
//	  upstream_protocol,
//	  public,
//	  schedule,
//	  runtime,
//	  handler,
//	  cpu_millicores,
//	  memory_mib,
//	  storage_mib,
//	  created_at
//	) VALUES (
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?
//	)
//	ON DUPLICATE KEY UPDATE id = id
func (q *Queries) InsertDeploymentResource(ctx context.Context, arg InsertDeploymentResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentResource,
		arg.ID,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AppID,
		arg.EnvironmentID,
		arg.Name,
		arg.Kind,
		arg.K8sName,
		arg.Image,
		arg.Command,
		arg.Port,
		arg.UpstreamProtocol,
		arg.Public,
		arg.Schedule,
		arg.Runtime,
		arg.Handler,
		arg.CpuMillicores,
		arg.MemoryMib,
		arg.StorageMib,
		arg.CreatedAt,
	)
	return err
}
