// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resource_delete.sql

package db

import (
	"context"
)

const deleteDeploymentResourcesByEnvironment = `-- name: DeleteDeploymentResourcesByEnvironment :exec
DELETE FROM deployment_resources WHERE environment_id = ?
`

// DeleteDeploymentResourcesByEnvironment
//
//	DELETE FROM deployment_resources WHERE environment_id = ?
func (q *Queries) DeleteDeploymentResourcesByEnvironment(ctx context.Context, environmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentResourcesByEnvironment, environmentID)
	return err
}
