// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resource_topology_update.sql

package db

import (
	"context"
	"database/sql"
)

const updateDeploymentResourceTopologyDesiredStatus = `-- name: UpdateDeploymentResourceTopologyDesiredStatus :exec
UPDATE deployment_topology
SET desired_status = ?, updated_at = ?
WHERE deployment_id = ?
  AND resource_id = ?
  AND region_id = ?
`

type UpdateDeploymentResourceTopologyDesiredStatusParams struct {
	DesiredStatus DeploymentTopologyDesiredStatus `db:"desired_status"`
	UpdatedAt     sql.NullInt64                   `db:"updated_at"`
	DeploymentID  string                          `db:"deployment_id"`
	ResourceID    string                          `db:"resource_id"`
	RegionID      string                          `db:"region_id"`
}

// UpdateDeploymentResourceTopologyDesiredStatus
//
//	UPDATE deployment_topology
//	SET desired_status = ?, updated_at = ?
//	WHERE deployment_id = ?
//	  AND resource_id = ?
//	  AND region_id = ?
func (q *Queries) UpdateDeploymentResourceTopologyDesiredStatus(ctx context.Context, arg UpdateDeploymentResourceTopologyDesiredStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentResourceTopologyDesiredStatus,
		arg.DesiredStatus,
		arg.UpdatedAt,
		arg.DeploymentID,
		arg.ResourceID,
		arg.RegionID,
	)
	return err
}
