// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_artifact_record.sql

package db

import (
	"context"
	"encoding/json"
)

const recordDeploymentArtifact = `-- name: RecordDeploymentArtifact :exec
INSERT INTO deployment_artifacts (
    id,
    deployment_id,
    workspace_id,
    project_id,
    app_id,
    environment_id,
    name,
    kind,
    storage_key,
    digest,
    size_bytes,
    content_type,
    metadata,
    created_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON DUPLICATE KEY UPDATE id = deployment_artifacts.id
`

type RecordDeploymentArtifactParams struct {
	ID            string                  `db:"id"`
	DeploymentID  string                  `db:"deployment_id"`
	WorkspaceID   string                  `db:"workspace_id"`
	ProjectID     string                  `db:"project_id"`
	AppID         string                  `db:"app_id"`
	EnvironmentID string                  `db:"environment_id"`
	Name          string                  `db:"name"`
	Kind          DeploymentArtifactsKind `db:"kind"`
	StorageKey    string                  `db:"storage_key"`
	Digest        string                  `db:"digest"`
	SizeBytes     uint64                  `db:"size_bytes"`
	ContentType   string                  `db:"content_type"`
	Metadata      json.RawMessage         `db:"metadata"`
	CreatedAt     int64                   `db:"created_at"`
}

// RecordDeploymentArtifact
//
//	INSERT INTO deployment_artifacts (
//	    id,
//	    deployment_id,
//	    workspace_id,
//	    project_id,
//	    app_id,
//	    environment_id,
//	    name,
//	    kind,
//	    storage_key,
//	    digest,
//	    size_bytes,
//	    content_type,
//	    metadata,
//	    created_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
//	ON DUPLICATE KEY UPDATE id = deployment_artifacts.id
func (q *Queries) RecordDeploymentArtifact(ctx context.Context, arg RecordDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, recordDeploymentArtifact,
		arg.ID,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AppID,
		arg.EnvironmentID,
		arg.Name,
		arg.Kind,
		arg.StorageKey,
		arg.Digest,
		arg.SizeBytes,
		arg.ContentType,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
