// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_manifest_find_by_deployment_id.sql

package db

import (
	"context"
)

const findDeploymentManifestByDeploymentID = `-- name: FindDeploymentManifestByDeploymentID :one
SELECT pk, deployment_id, workspace_id, project_id, app_id, environment_id, schema_version, fingerprint, adapter_id, output_mode, manifest, created_at
FROM deployment_manifests
WHERE deployment_id = ?
`

// FindDeploymentManifestByDeploymentID
//
//	SELECT pk, deployment_id, workspace_id, project_id, app_id, environment_id, schema_version, fingerprint, adapter_id, output_mode, manifest, created_at
//	FROM deployment_manifests
//	WHERE deployment_id = ?
func (q *Queries) FindDeploymentManifestByDeploymentID(ctx context.Context, deploymentID string) (DeploymentManifest, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentManifestByDeploymentID, deploymentID)
	var i DeploymentManifest
	err := row.Scan(
		&i.Pk,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.SchemaVersion,
		&i.Fingerprint,
		&i.AdapterID,
		&i.OutputMode,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}
