// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_assign.sql

package db

import (
	"context"
	"database/sql"
)

const assignDeploymentTarget = `-- name: AssignDeploymentTarget :exec
UPDATE deployment_targets
SET
  previous_deployment_id = deployment_id,
  deployment_id = ?,
  updated_at = ?
WHERE id = ?
`

type AssignDeploymentTargetParams struct {
	DeploymentID string        `db:"deployment_id"`
	UpdatedAt    sql.NullInt64 `db:"updated_at"`
	ID           string        `db:"id"`
}

// AssignDeploymentTarget
//
//	UPDATE deployment_targets
//	SET
//	  previous_deployment_id = deployment_id,
//	  deployment_id = ?,
//	  updated_at = ?
//	WHERE id = ?
func (q *Queries) AssignDeploymentTarget(ctx context.Context, arg AssignDeploymentTargetParams) error {
	_, err := q.db.ExecContext(ctx, assignDeploymentTarget, arg.DeploymentID, arg.UpdatedAt, arg.ID)
	return err
}
