// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_min_replicas_by_deployment.sql

package db

import (
	"context"
)

const findDeploymentTopologyMinReplicas = `-- name: FindDeploymentTopologyMinReplicas :many
SELECT dt.resource_id, dt.region_id, dt.autoscaling_replicas_min
FROM deployment_topology dt
LEFT JOIN deployment_resources dr ON dt.resource_id = dr.id
WHERE dt.deployment_id = ?
	AND (dt.resource_id = '' OR dr.kind != 'cron')
`

type FindDeploymentTopologyMinReplicasRow struct {
	ResourceID             string `db:"resource_id"`
	RegionID               string `db:"region_id"`
	AutoscalingReplicasMin uint32 `db:"autoscaling_replicas_min"`
}

// Returns the per-region minimum replica requirement for a deployment.
// Used by deploy and wake workflows to compute whether enough regions are
// healthy before a deployment is considered ready.
//
//	SELECT dt.resource_id, dt.region_id, dt.autoscaling_replicas_min
//	FROM deployment_topology dt
//	LEFT JOIN deployment_resources dr ON dt.resource_id = dr.id
//	WHERE dt.deployment_id = ?
//		AND (dt.resource_id = '' OR dr.kind != 'cron')
func (q *Queries) FindDeploymentTopologyMinReplicas(ctx context.Context, deploymentID string) ([]FindDeploymentTopologyMinReplicasRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeploymentTopologyMinReplicas, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDeploymentTopologyMinReplicasRow
	for rows.Next() {
		var i FindDeploymentTopologyMinReplicasRow
		if err := rows.Scan(&i.ResourceID, &i.RegionID, &i.AutoscalingReplicasMin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
