// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_list_by_pull_request.sql

package db

import (
	"context"
	"database/sql"
)

const listDeploymentsForPullRequest = `-- name: ListDeploymentsForPullRequest :many
SELECT d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.` + "`" + `trigger` + "`" + `, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at
FROM deployments AS d
JOIN environments AS e ON e.id = d.environment_id
JOIN github_repo_connections AS c ON c.app_id = d.app_id
WHERE c.installation_id = ?
  AND c.repository_id = ?
  AND e.slug = 'preview'
  AND IF(
    CAST(? AS SIGNED) = 1,
    d.pr_number = ?
      AND d.fork_repository_full_name = ?,
    d.pr_number IS NULL
      AND d.git_branch = ?
  )
ORDER BY d.created_at DESC
`

type ListDeploymentsForPullRequestParams struct {
	InstallationID         int64          `db:"installation_id"`
	RepositoryID           int64          `db:"repository_id"`
	IsForkPr               int64          `db:"is_fork_pr"`
	PrNumber               sql.NullInt64  `db:"pr_number"`
	ForkRepositoryFullName sql.NullString `db:"fork_repository_full_name"`
	Branch                 sql.NullString `db:"branch"`
}

// ListDeploymentsForPullRequest
//
//	SELECT d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.upstream_protocol, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.invocation_id, d.status, d.`trigger`, d.triggered_by, d.trigger_reason, d.created_at, d.updated_at
//	FROM deployments AS d
//	JOIN environments AS e ON e.id = d.environment_id
//	JOIN github_repo_connections AS c ON c.app_id = d.app_id
//	WHERE c.installation_id = ?
//	  AND c.repository_id = ?
//	  AND e.slug = 'preview'
//	  AND IF(
//	    CAST(? AS SIGNED) = 1,
//	    d.pr_number = ?
//	      AND d.fork_repository_full_name = ?,
//	    d.pr_number IS NULL
//	      AND d.git_branch = ?
//	  )
//	ORDER BY d.created_at DESC
func (q *Queries) ListDeploymentsForPullRequest(ctx context.Context, arg ListDeploymentsForPullRequestParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsForPullRequest,
		arg.InstallationID,
		arg.RepositoryID,
		arg.IsForkPr,
		arg.PrNumber,
		arg.ForkRepositoryFullName,
		arg.Branch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.K8sName,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.AppID,
			&i.Image,
			&i.BuildID,
			&i.GitCommitSha,
			&i.GitBranch,
			&i.GitCommitMessage,
			&i.GitCommitAuthorHandle,
			&i.GitCommitAuthorAvatarUrl,
			&i.GitCommitTimestamp,
			&i.SentinelConfig,
			&i.CpuMillicores,
			&i.MemoryMib,
			&i.StorageMib,
			&i.DesiredState,
			&i.EncryptedEnvironmentVariables,
			&i.Command,
			&i.Port,
			&i.ShutdownSignal,
			&i.UpstreamProtocol,
			&i.Healthcheck,
			&i.PrNumber,
			&i.ForkRepositoryFullName,
			&i.GithubDeploymentID,
			&i.InvocationID,
			&i.Status,
			&i.Trigger,
			&i.TriggeredBy,
			&i.TriggerReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
