// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_manifest_insert.sql

package db

import (
	"context"
	"encoding/json"
)

const insertDeploymentManifest = `-- name: InsertDeploymentManifest :exec
INSERT INTO deployment_manifests (
    deployment_id,
    workspace_id,
    project_id,
    app_id,
    environment_id,
    schema_version,
    fingerprint,
    adapter_id,
    output_mode,
    manifest,
    created_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertDeploymentManifestParams struct {
	DeploymentID  string                        `db:"deployment_id"`
	WorkspaceID   string                        `db:"workspace_id"`
	ProjectID     string                        `db:"project_id"`
	AppID         string                        `db:"app_id"`
	EnvironmentID string                        `db:"environment_id"`
	SchemaVersion uint64                        `db:"schema_version"`
	Fingerprint   string                        `db:"fingerprint"`
	AdapterID     string                        `db:"adapter_id"`
	OutputMode    DeploymentManifestsOutputMode `db:"output_mode"`
	Manifest      json.RawMessage               `db:"manifest"`
	CreatedAt     int64                         `db:"created_at"`
}

// InsertDeploymentManifest
//
//	INSERT INTO deployment_manifests (
//	    deployment_id,
//	    workspace_id,
//	    project_id,
//	    app_id,
//	    environment_id,
//	    schema_version,
//	    fingerprint,
//	    adapter_id,
//	    output_mode,
//	    manifest,
//	    created_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertDeploymentManifest(ctx context.Context, arg InsertDeploymentManifestParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentManifest,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AppID,
		arg.EnvironmentID,
		arg.SchemaVersion,
		arg.Fingerprint,
		arg.AdapterID,
		arg.OutputMode,
		arg.Manifest,
		arg.CreatedAt,
	)
	return err
}
