// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertDeploymentTarget = `-- name: InsertDeploymentTarget :exec
INSERT INTO deployment_targets (
  id,
  workspace_id,
  project_id,
  app_id,
  environment_id,
  kind,
  target_key,
  deployment_id,
  previous_deployment_id,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE id = id
`

type InsertDeploymentTargetParams struct {
	ID                   string                `db:"id"`
	WorkspaceID          string                `db:"workspace_id"`
	ProjectID            string                `db:"project_id"`
	AppID                string                `db:"app_id"`
	EnvironmentID        string                `db:"environment_id"`
	Kind                 DeploymentTargetsKind `db:"kind"`
	TargetKey            string                `db:"target_key"`
	DeploymentID         string                `db:"deployment_id"`
	PreviousDeploymentID sql.NullString        `db:"previous_deployment_id"`
	CreatedAt            int64                 `db:"created_at"`
	UpdatedAt            sql.NullInt64         `db:"updated_at"`
}

// InsertDeploymentTarget
//
//	INSERT INTO deployment_targets (
//	  id,
//	  workspace_id,
//	  project_id,
//	  app_id,
//	  environment_id,
//	  kind,
//	  target_key,
//	  deployment_id,
//	  previous_deployment_id,
//	  created_at,
//	  updated_at
//	) VALUES (
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?
//	)
//	ON DUPLICATE KEY UPDATE id = id
func (q *Queries) InsertDeploymentTarget(ctx context.Context, arg InsertDeploymentTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentTarget,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AppID,
		arg.EnvironmentID,
		arg.Kind,
		arg.TargetKey,
		arg.DeploymentID,
		arg.PreviousDeploymentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
