// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_target_assignment_record.sql

package db

import (
	"context"
	"database/sql"
)

const recordDeploymentTargetAssignment = `-- name: RecordDeploymentTargetAssignment :exec
INSERT INTO deployment_target_assignments (
  id,
  target_id,
  workspace_id,
  project_id,
  app_id,
  environment_id,
  deployment_id,
  previous_deployment_id,
  reason,
  operation_id,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE id = id
`

type RecordDeploymentTargetAssignmentParams struct {
	ID                   string                            `db:"id"`
	TargetID             string                            `db:"target_id"`
	WorkspaceID          string                            `db:"workspace_id"`
	ProjectID            string                            `db:"project_id"`
	AppID                string                            `db:"app_id"`
	EnvironmentID        string                            `db:"environment_id"`
	DeploymentID         string                            `db:"deployment_id"`
	PreviousDeploymentID sql.NullString                    `db:"previous_deployment_id"`
	Reason               DeploymentTargetAssignmentsReason `db:"reason"`
	OperationID          string                            `db:"operation_id"`
	CreatedAt            int64                             `db:"created_at"`
}

// RecordDeploymentTargetAssignment
//
//	INSERT INTO deployment_target_assignments (
//	  id,
//	  target_id,
//	  workspace_id,
//	  project_id,
//	  app_id,
//	  environment_id,
//	  deployment_id,
//	  previous_deployment_id,
//	  reason,
//	  operation_id,
//	  created_at
//	) VALUES (
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?,
//	  ?
//	)
//	ON DUPLICATE KEY UPDATE id = id
func (q *Queries) RecordDeploymentTargetAssignment(ctx context.Context, arg RecordDeploymentTargetAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, recordDeploymentTargetAssignment,
		arg.ID,
		arg.TargetID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AppID,
		arg.EnvironmentID,
		arg.DeploymentID,
		arg.PreviousDeploymentID,
		arg.Reason,
		arg.OperationID,
		arg.CreatedAt,
	)
	return err
}
