// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_delete_by_environment.sql

package db

import (
	"context"
)

const deleteDeploymentsByEnvironmentId = `-- name: DeleteDeploymentsByEnvironmentId :exec
DELETE deployment_manifests, deployments
FROM deployments
LEFT JOIN deployment_manifests ON deployment_manifests.deployment_id = deployments.id
WHERE deployments.environment_id = ?
`

// DeleteDeploymentsByEnvironmentId
//
//	DELETE deployment_manifests, deployments
//	FROM deployments
//	LEFT JOIN deployment_manifests ON deployment_manifests.deployment_id = deployments.id
//	WHERE deployments.environment_id = ?
func (q *Queries) DeleteDeploymentsByEnvironmentId(ctx context.Context, environmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentsByEnvironmentId, environmentID)
	return err
}
