// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_update.sql

package db

import (
	"context"
	"database/sql"
)

const updateEnvironment = `-- name: UpdateEnvironment :exec
UPDATE environments
SET slug = ?,
    description = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateEnvironmentParams struct {
	Slug        string        `db:"slug"`
	Description string        `db:"description"`
	UpdatedAt   sql.NullInt64 `db:"updated_at"`
	ID          string        `db:"id"`
}

// UpdateEnvironment
//
//	UPDATE environments
//	SET slug = ?,
//	    description = ?,
//	    updated_at = ?
//	WHERE id = ?
func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvironment,
		arg.Slug,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
