// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_update_delete_protection.sql

package db

import (
	"context"
	"database/sql"
)

const updateEnvironmentDeleteProtection = `-- name: UpdateEnvironmentDeleteProtection :exec
UPDATE environments
SET delete_protection = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateEnvironmentDeleteProtectionParams struct {
	DeleteProtection sql.NullBool  `db:"delete_protection"`
	UpdatedAt        sql.NullInt64 `db:"updated_at"`
	ID               string        `db:"id"`
}

// UpdateEnvironmentDeleteProtection
//
//	UPDATE environments
//	SET delete_protection = ?,
//	    updated_at = ?
//	WHERE id = ?
func (q *Queries) UpdateEnvironmentDeleteProtection(ctx context.Context, arg UpdateEnvironmentDeleteProtectionParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvironmentDeleteProtection, arg.DeleteProtection, arg.UpdatedAt, arg.ID)
	return err
}
