// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_count_deployments.sql

package db

import (
	"context"
)

const countDeploymentsByEnvironmentID = `-- name: CountDeploymentsByEnvironmentID :one
SELECT COUNT(*)
FROM deployments
WHERE environment_id = ?
`

// CountDeploymentsByEnvironmentID
//
//	SELECT COUNT(*)
//	FROM deployments
//	WHERE environment_id = ?
func (q *Queries) CountDeploymentsByEnvironmentID(ctx context.Context, environmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeploymentsByEnvironmentID, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
