// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: horizontal_autoscaling_policy_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertHorizontalAutoscalingPolicy = `-- name: InsertHorizontalAutoscalingPolicy :exec
INSERT INTO horizontal_autoscaling_policies (
    id,
    workspace_id,
    replicas_min,
    replicas_max,
    memory_threshold,
    cpu_threshold,
    rps_threshold,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertHorizontalAutoscalingPolicyParams struct {
	ID              string        `db:"id"`
	WorkspaceID     string        `db:"workspace_id"`
	ReplicasMin     int32         `db:"replicas_min"`
	ReplicasMax     int32         `db:"replicas_max"`
	MemoryThreshold sql.NullInt16 `db:"memory_threshold"`
	CpuThreshold    sql.NullInt16 `db:"cpu_threshold"`
	RpsThreshold    sql.NullInt16 `db:"rps_threshold"`
	CreatedAt       int64         `db:"created_at"`
	UpdatedAt       sql.NullInt64 `db:"updated_at"`
}

// InsertHorizontalAutoscalingPolicy
//
//	INSERT INTO horizontal_autoscaling_policies (
//	    id,
//	    workspace_id,
//	    replicas_min,
//	    replicas_max,
//	    memory_threshold,
//	    cpu_threshold,
//	    rps_threshold,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertHorizontalAutoscalingPolicy(ctx context.Context, arg InsertHorizontalAutoscalingPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertHorizontalAutoscalingPolicy,
		arg.ID,
		arg.WorkspaceID,
		arg.ReplicasMin,
		arg.ReplicasMax,
		arg.MemoryThreshold,
		arg.CpuThreshold,
		arg.RpsThreshold,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
