// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_delete_by_deployment.sql

package db

import (
	"context"
)

const deleteFrontlineRoutesByDeploymentID = `-- name: DeleteFrontlineRoutesByDeploymentID :exec
DELETE FROM frontline_routes
WHERE deployment_id = ?
`

// DeleteFrontlineRoutesByDeploymentID
//
//	DELETE FROM frontline_routes
//	WHERE deployment_id = ?
func (q *Queries) DeleteFrontlineRoutesByDeploymentID(ctx context.Context, deploymentID string) error {
	_, err := q.db.ExecContext(ctx, deleteFrontlineRoutesByDeploymentID, deploymentID)
	return err
}
