// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_project_connection_find_by_project_id.sql

package db

import (
	"context"
)

const listSlackProjectConnectionsByProjectId = `-- name: ListSlackProjectConnectionsByProjectId :many
SELECT
    pk,
    id,
    workspace_id,
    project_id,
    installation_id,
    channel_id,
    channel_name,
    notify_production,
    notify_previews,
    created_at,
    updated_at
FROM slack_project_connections
WHERE project_id = ?
`

// ListSlackProjectConnectionsByProjectId
//
//	SELECT
//	    pk,
//	    id,
//	    workspace_id,
//	    project_id,
//	    installation_id,
//	    channel_id,
//	    channel_name,
//	    notify_production,
//	    notify_previews,
//	    created_at,
//	    updated_at
//	FROM slack_project_connections
//	WHERE project_id = ?
func (q *Queries) ListSlackProjectConnectionsByProjectId(ctx context.Context, projectID string) ([]SlackProjectConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSlackProjectConnectionsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlackProjectConnection
	for rows.Next() {
		var i SlackProjectConnection
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.InstallationID,
			&i.ChannelID,
			&i.ChannelName,
			&i.NotifyProduction,
			&i.NotifyPreviews,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
