// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_project_connection_find_by_project_id.sql

package db

import (
	"context"
)

const findSlackProjectConnectionByProjectId = `-- name: FindSlackProjectConnectionByProjectId :one
SELECT
    pk,
    id,
    workspace_id,
    project_id,
    installation_id,
    channel_id,
    channel_name,
    include_previews,
    approval_policy,
    created_at,
    updated_at
FROM slack_project_connections
WHERE project_id = ?
`

// FindSlackProjectConnectionByProjectId
//
//	SELECT
//	    pk,
//	    id,
//	    workspace_id,
//	    project_id,
//	    installation_id,
//	    channel_id,
//	    channel_name,
//	    include_previews,
//	    approval_policy,
//	    created_at,
//	    updated_at
//	FROM slack_project_connections
//	WHERE project_id = ?
func (q *Queries) FindSlackProjectConnectionByProjectId(ctx context.Context, projectID string) (SlackProjectConnection, error) {
	row := q.db.QueryRowContext(ctx, findSlackProjectConnectionByProjectId, projectID)
	var i SlackProjectConnection
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.InstallationID,
		&i.ChannelID,
		&i.ChannelName,
		&i.IncludePreviews,
		&i.ApprovalPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
