// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_installation_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertSlackInstallation = `-- name: InsertSlackInstallation :exec
INSERT INTO slack_installations (
    id,
    workspace_id,
    team_id,
    bot_token,
    bot_user_id,
    installed_by_user_id,
    created_at,
    updated_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertSlackInstallationParams struct {
	ID                string        `db:"id"`
	WorkspaceID       string        `db:"workspace_id"`
	TeamID            string        `db:"team_id"`
	BotToken          string        `db:"bot_token"`
	BotUserID         string        `db:"bot_user_id"`
	InstalledByUserID string        `db:"installed_by_user_id"`
	CreatedAt         int64         `db:"created_at"`
	UpdatedAt         sql.NullInt64 `db:"updated_at"`
}

// InsertSlackInstallation
//
//	INSERT INTO slack_installations (
//	    id,
//	    workspace_id,
//	    team_id,
//	    bot_token,
//	    bot_user_id,
//	    installed_by_user_id,
//	    created_at,
//	    updated_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertSlackInstallation(ctx context.Context, arg InsertSlackInstallationParams) error {
	_, err := q.db.ExecContext(ctx, insertSlackInstallation,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.BotToken,
		arg.BotUserID,
		arg.InstalledByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
