// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_installation_find_by_id.sql

package db

import (
	"context"
)

const findSlackInstallationById = `-- name: FindSlackInstallationById :one
SELECT
    pk,
    id,
    workspace_id,
    team_id,
    bot_token,
    bot_user_id,
    installed_by_user_id,
    created_at,
    updated_at
FROM slack_installations
WHERE id = ?
`

// FindSlackInstallationById
//
//	SELECT
//	    pk,
//	    id,
//	    workspace_id,
//	    team_id,
//	    bot_token,
//	    bot_user_id,
//	    installed_by_user_id,
//	    created_at,
//	    updated_at
//	FROM slack_installations
//	WHERE id = ?
func (q *Queries) FindSlackInstallationById(ctx context.Context, id string) (SlackInstallation, error) {
	row := q.db.QueryRowContext(ctx, findSlackInstallationById, id)
	var i SlackInstallation
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.BotToken,
		&i.BotUserID,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
