// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_project_connection_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertSlackProjectConnection = `-- name: InsertSlackProjectConnection :exec
INSERT INTO slack_project_connections (
    id,
    workspace_id,
    project_id,
    installation_id,
    channel_id,
    channel_name,
    notify_production,
    notify_previews,
    created_at,
    updated_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertSlackProjectConnectionParams struct {
	ID               string        `db:"id"`
	WorkspaceID      string        `db:"workspace_id"`
	ProjectID        string        `db:"project_id"`
	InstallationID   string        `db:"installation_id"`
	ChannelID        string        `db:"channel_id"`
	ChannelName      string        `db:"channel_name"`
	NotifyProduction bool          `db:"notify_production"`
	NotifyPreviews   bool          `db:"notify_previews"`
	CreatedAt        int64         `db:"created_at"`
	UpdatedAt        sql.NullInt64 `db:"updated_at"`
}

// InsertSlackProjectConnection
//
//	INSERT INTO slack_project_connections (
//	    id,
//	    workspace_id,
//	    project_id,
//	    installation_id,
//	    channel_id,
//	    channel_name,
//	    notify_production,
//	    notify_previews,
//	    created_at,
//	    updated_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertSlackProjectConnection(ctx context.Context, arg InsertSlackProjectConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertSlackProjectConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.InstallationID,
		arg.ChannelID,
		arg.ChannelName,
		arg.NotifyProduction,
		arg.NotifyPreviews,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
