// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// FindKeyForVerification loads a key by its SHA-256 hash together with its
	// workspace status, RBAC roles and permissions, identity, and rate limit
	// configuration in a single round trip. Roles, permissions, and rate limits
	// are returned as JSON arrays via JSON_ARRAYAGG so the caller can unmarshal
	// them into typed Go structs. Key-level and identity-level rate limits are
	// unioned so that both sources are available for the verification pipeline.
	//
	// hash_idx resolves the key row first. Correlated aggregates drive from
	// keys_roles / keys_permissions / ratelimits keyed by k.id so MySQL does not
	// scan workspace-wide role or permission catalogs (see EXPLAIN plans).
	//
	//  SELECT
	//    k.id,
	//    k.key_auth_id,
	//    k.workspace_id,
	//    k.for_workspace_id,
	//    k.name,
	//    k.meta,
	//    k.expires,
	//    k.deleted_at_m,
	//    k.refill_day,
	//    k.refill_amount,
	//    k.last_refill_at,
	//    k.enabled,
	//    k.remaining_requests,
	//    k.pending_migration_id,
	//    a.ip_whitelist,
	//    a.workspace_id AS api_workspace_id,
	//    a.id AS api_id,
	//    a.deleted_at_m AS api_deleted_at_m,
	//    COALESCE(
	//      (
	//        SELECT
	//          JSON_ARRAYAGG(r.name)
	//        FROM
	//          keys_roles kr
	//          STRAIGHT_JOIN roles r ON r.id = kr.role_id
	//        WHERE
	//          kr.key_id = k.id
	//      ),
	//      JSON_ARRAY()
	//    ) AS roles,
	//    COALESCE(
	//      (
	//        SELECT
	//          JSON_ARRAYAGG(slug)
	//        FROM
	//          (
	//            SELECT
	//              p.slug
	//            FROM
	//              keys_permissions kp
	//              STRAIGHT_JOIN permissions p ON p.id = kp.permission_id
	//            WHERE
	//              kp.key_id = k.id
	//            UNION ALL
	//            SELECT
	//              p.slug
	//            FROM
	//              keys_roles kr
	//              STRAIGHT_JOIN roles_permissions rp ON rp.role_id = kr.role_id
	//              STRAIGHT_JOIN permissions p ON p.id = rp.permission_id
	//            WHERE
	//              kr.key_id = k.id
	//          ) combined_perms
	//      ),
	//      JSON_ARRAY()
	//    ) AS permissions,
	//    COALESCE(
	//      (
	//        SELECT
	//          JSON_ARRAYAGG(
	//            JSON_OBJECT(
	//              'id',
	//              rl.id,
	//              'name',
	//              rl.name,
	//              'key_id',
	//              rl.key_id,
	//              'identity_id',
	//              rl.identity_id,
	//              'limit',
	//              rl.`limit`,
	//              'duration',
	//              rl.duration,
	//              'auto_apply',
	//              rl.auto_apply
	//            )
	//          )
	//        FROM
	//          (
	//            SELECT
	//              rl.id,
	//              rl.name,
	//              rl.key_id,
	//              rl.identity_id,
	//              rl.`limit`,
	//              rl.duration,
	//              rl.auto_apply
	//            FROM
	//              `ratelimits` rl
	//            WHERE
	//              rl.key_id = k.id
	//            UNION ALL
	//            SELECT
	//              rl.id,
	//              rl.name,
	//              rl.key_id,
	//              rl.identity_id,
	//              rl.`limit`,
	//              rl.duration,
	//              rl.auto_apply
	//            FROM
	//              `ratelimits` rl
	//            WHERE
	//              k.identity_id IS NOT NULL
	//              AND rl.identity_id = k.identity_id
	//          ) rl
	//      ),
	//      JSON_ARRAY()
	//    ) AS ratelimits,
	//    i.id AS identity_id,
	//    i.external_id,
	//    i.meta AS identity_meta,
	//    ka.deleted_at_m AS key_auth_deleted_at_m,
	//    ws.enabled AS workspace_enabled,
	//    fws.enabled AS for_workspace_enabled
	//  FROM
	//    `keys` k
	//    JOIN apis a ON a.key_auth_id = k.key_auth_id
	//    JOIN key_auth ka ON ka.id = k.key_auth_id
	//    JOIN workspaces ws ON ws.id = k.workspace_id
	//    LEFT JOIN workspaces fws ON fws.id = k.for_workspace_id
	//    LEFT JOIN identities i ON k.identity_id = i.id
	//    AND i.deleted = 0
	//  WHERE
	//    k.hash = ?
	//    AND k.deleted_at_m IS NULL
	FindKeyForVerification(ctx context.Context, db DBTX, hash string) (FindKeyForVerificationRow, error)
	// FindKeyMigrationByID returns the migration record for a key, scoped to
	// the given workspace. The algorithm field determines which hashing scheme
	// the caller should use for the initial lookup before migrating to SHA-256.
	//
	//  SELECT
	//      id,
	//      workspace_id,
	//      algorithm
	//  FROM key_migrations
	//  WHERE id = ?
	//  and workspace_id = ?
	FindKeyMigrationByID(ctx context.Context, db DBTX, arg FindKeyMigrationByIDParams) (FindKeyMigrationByIDRow, error)
	// FindQuotaByWorkspaceID returns the quota row for a workspace, used to
	// enforce per-workspace API rate limits on root key requests. NULL
	// limit/duration means unlimited; zero means explicitly blocked.
	//
	//  SELECT pk, workspace_id, requests_per_month, logs_retention_days, audit_logs_retention_days, team, ratelimit_api_limit, ratelimit_api_duration, allocated_cpu_millicores_total, allocated_memory_mib_total, allocated_storage_mib_total, max_cpu_millicores_per_instance, max_memory_mib_per_instance, max_storage_mib_per_instance, max_concurrent_builds
	//  FROM `quota`
	//  WHERE workspace_id = ?
	FindQuotaByWorkspaceID(ctx context.Context, db DBTX, workspaceID string) (Quotas, error)
	// UpdateKeyHashAndMigration re-hashes a key to SHA-256 after a successful
	// on-demand migration and clears the pending migration marker so future
	// lookups use the standard hash path.
	//
	//  UPDATE `keys`
	//  SET
	//      hash = ?,
	//      pending_migration_id = ?,
	//      start = ?,
	//      updated_at_m = ?
	//  WHERE id = ?
	UpdateKeyHashAndMigration(ctx context.Context, db DBTX, arg UpdateKeyHashAndMigrationParams) error
}

var _ Querier = (*Queries)(nil)
