-- name: InsertDeploymentResource :exec
INSERT INTO deployment_resources (
  id,
  deployment_id,
  workspace_id,
  project_id,
  app_id,
  environment_id,
  name,
  kind,
  k8s_name,
  image,
  command,
  port,
  upstream_protocol,
  public,
  schedule,
  runtime,
  handler,
  cpu_millicores,
  memory_mib,
  storage_mib,
  created_at
) VALUES (
  sqlc.arg(id),
  sqlc.arg(deployment_id),
  sqlc.arg(workspace_id),
  sqlc.arg(project_id),
  sqlc.arg(app_id),
  sqlc.arg(environment_id),
  sqlc.arg(name),
  sqlc.arg(kind),
  sqlc.narg(k8s_name),
  sqlc.narg(image),
  sqlc.arg(command),
  sqlc.arg(port),
  sqlc.arg(upstream_protocol),
  sqlc.arg(public),
  sqlc.narg(schedule),
  sqlc.narg(runtime),
  sqlc.narg(handler),
  sqlc.arg(cpu_millicores),
  sqlc.arg(memory_mib),
  sqlc.arg(storage_mib),
  sqlc.arg(created_at)
)
ON DUPLICATE KEY UPDATE id = id;
