type: object
required:
  - project
  - app
  - environmentSlug
properties:
  project:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  app:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  environmentSlug:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  git:
    "$ref": "./DeploymentSourceGit.yaml"
  image:
    "$ref": "./DeploymentSourceImage.yaml"
  deployment:
    "$ref": "./DeploymentSourceDeployment.yaml"
oneOf:
  - required: [image]
  - required: [git]
  - required: [deployment]
description: Create a deployment. Provide exactly one of git, image, or deployment.
